# Generated by Django 5.1.4 on 2024-12-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beats', max_length=100)),
                ('price_mp3', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('price_wav', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('price_trackout', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('price_exclusive', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mastering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mastering', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mixing', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mixing & Mastering', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Recording', max_length=100)),
                ('timeslot', models.DateTimeField()),
                ('price_morning', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_afternoon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_evening', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('details', models.TextField()),
            ],
        ),
    ]
